/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreenReaderRouteImport } from './routes/screen-reader'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as SlugTendersRouteImport } from './routes/$slug.tenders'
import { Route as SlugPublicRepresentativesRouteImport } from './routes/$slug.public-representatives'
import { Route as SlugOrganizationalChartRouteImport } from './routes/$slug.organizational-chart'
import { Route as SlugNoticesRouteImport } from './routes/$slug.notices'
import { Route as SlugNewsRouteImport } from './routes/$slug.news'
import { Route as SlugMediaCoverageRouteImport } from './routes/$slug.media-coverage'
import { Route as SlugGrievanceRouteImport } from './routes/$slug.grievance'
import { Route as SlugGalleryRouteImport } from './routes/$slug.gallery'
import { Route as SlugDepartmentsRouteImport } from './routes/$slug.departments'
import { Route as SlugCouncilRouteImport } from './routes/$slug.council'
import { Route as SlugContactRouteImport } from './routes/$slug.contact'
import { Route as SlugCoOptionMembersRouteImport } from './routes/$slug.co-option-members'
import { Route as SlugChairpersonRouteImport } from './routes/$slug.chairperson'
import { Route as SlugAboutRouteImport } from './routes/$slug.about'

const ScreenReaderRoute = ScreenReaderRouteImport.update({
  id: '/screen-reader',
  path: '/screen-reader',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugTendersRoute = SlugTendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => SlugRoute,
} as any)
const SlugPublicRepresentativesRoute =
  SlugPublicRepresentativesRouteImport.update({
    id: '/public-representatives',
    path: '/public-representatives',
    getParentRoute: () => SlugRoute,
  } as any)
const SlugOrganizationalChartRoute = SlugOrganizationalChartRouteImport.update({
  id: '/organizational-chart',
  path: '/organizational-chart',
  getParentRoute: () => SlugRoute,
} as any)
const SlugNoticesRoute = SlugNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => SlugRoute,
} as any)
const SlugNewsRoute = SlugNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => SlugRoute,
} as any)
const SlugMediaCoverageRoute = SlugMediaCoverageRouteImport.update({
  id: '/media-coverage',
  path: '/media-coverage',
  getParentRoute: () => SlugRoute,
} as any)
const SlugGrievanceRoute = SlugGrievanceRouteImport.update({
  id: '/grievance',
  path: '/grievance',
  getParentRoute: () => SlugRoute,
} as any)
const SlugGalleryRoute = SlugGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => SlugRoute,
} as any)
const SlugDepartmentsRoute = SlugDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => SlugRoute,
} as any)
const SlugCouncilRoute = SlugCouncilRouteImport.update({
  id: '/council',
  path: '/council',
  getParentRoute: () => SlugRoute,
} as any)
const SlugContactRoute = SlugContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SlugRoute,
} as any)
const SlugCoOptionMembersRoute = SlugCoOptionMembersRouteImport.update({
  id: '/co-option-members',
  path: '/co-option-members',
  getParentRoute: () => SlugRoute,
} as any)
const SlugChairpersonRoute = SlugChairpersonRouteImport.update({
  id: '/chairperson',
  path: '/chairperson',
  getParentRoute: () => SlugRoute,
} as any)
const SlugAboutRoute = SlugAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/screen-reader': typeof ScreenReaderRoute
  '/$slug/about': typeof SlugAboutRoute
  '/$slug/chairperson': typeof SlugChairpersonRoute
  '/$slug/co-option-members': typeof SlugCoOptionMembersRoute
  '/$slug/contact': typeof SlugContactRoute
  '/$slug/council': typeof SlugCouncilRoute
  '/$slug/departments': typeof SlugDepartmentsRoute
  '/$slug/gallery': typeof SlugGalleryRoute
  '/$slug/grievance': typeof SlugGrievanceRoute
  '/$slug/media-coverage': typeof SlugMediaCoverageRoute
  '/$slug/news': typeof SlugNewsRoute
  '/$slug/notices': typeof SlugNoticesRoute
  '/$slug/organizational-chart': typeof SlugOrganizationalChartRoute
  '/$slug/public-representatives': typeof SlugPublicRepresentativesRoute
  '/$slug/tenders': typeof SlugTendersRoute
  '/admin/login': typeof AdminLoginRoute
  '/$slug/': typeof SlugIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/screen-reader': typeof ScreenReaderRoute
  '/$slug/about': typeof SlugAboutRoute
  '/$slug/chairperson': typeof SlugChairpersonRoute
  '/$slug/co-option-members': typeof SlugCoOptionMembersRoute
  '/$slug/contact': typeof SlugContactRoute
  '/$slug/council': typeof SlugCouncilRoute
  '/$slug/departments': typeof SlugDepartmentsRoute
  '/$slug/gallery': typeof SlugGalleryRoute
  '/$slug/grievance': typeof SlugGrievanceRoute
  '/$slug/media-coverage': typeof SlugMediaCoverageRoute
  '/$slug/news': typeof SlugNewsRoute
  '/$slug/notices': typeof SlugNoticesRoute
  '/$slug/organizational-chart': typeof SlugOrganizationalChartRoute
  '/$slug/public-representatives': typeof SlugPublicRepresentativesRoute
  '/$slug/tenders': typeof SlugTendersRoute
  '/admin/login': typeof AdminLoginRoute
  '/$slug': typeof SlugIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/screen-reader': typeof ScreenReaderRoute
  '/$slug/about': typeof SlugAboutRoute
  '/$slug/chairperson': typeof SlugChairpersonRoute
  '/$slug/co-option-members': typeof SlugCoOptionMembersRoute
  '/$slug/contact': typeof SlugContactRoute
  '/$slug/council': typeof SlugCouncilRoute
  '/$slug/departments': typeof SlugDepartmentsRoute
  '/$slug/gallery': typeof SlugGalleryRoute
  '/$slug/grievance': typeof SlugGrievanceRoute
  '/$slug/media-coverage': typeof SlugMediaCoverageRoute
  '/$slug/news': typeof SlugNewsRoute
  '/$slug/notices': typeof SlugNoticesRoute
  '/$slug/organizational-chart': typeof SlugOrganizationalChartRoute
  '/$slug/public-representatives': typeof SlugPublicRepresentativesRoute
  '/$slug/tenders': typeof SlugTendersRoute
  '/admin/login': typeof AdminLoginRoute
  '/$slug/': typeof SlugIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/screen-reader'
    | '/$slug/about'
    | '/$slug/chairperson'
    | '/$slug/co-option-members'
    | '/$slug/contact'
    | '/$slug/council'
    | '/$slug/departments'
    | '/$slug/gallery'
    | '/$slug/grievance'
    | '/$slug/media-coverage'
    | '/$slug/news'
    | '/$slug/notices'
    | '/$slug/organizational-chart'
    | '/$slug/public-representatives'
    | '/$slug/tenders'
    | '/admin/login'
    | '/$slug/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/screen-reader'
    | '/$slug/about'
    | '/$slug/chairperson'
    | '/$slug/co-option-members'
    | '/$slug/contact'
    | '/$slug/council'
    | '/$slug/departments'
    | '/$slug/gallery'
    | '/$slug/grievance'
    | '/$slug/media-coverage'
    | '/$slug/news'
    | '/$slug/notices'
    | '/$slug/organizational-chart'
    | '/$slug/public-representatives'
    | '/$slug/tenders'
    | '/admin/login'
    | '/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/screen-reader'
    | '/$slug/about'
    | '/$slug/chairperson'
    | '/$slug/co-option-members'
    | '/$slug/contact'
    | '/$slug/council'
    | '/$slug/departments'
    | '/$slug/gallery'
    | '/$slug/grievance'
    | '/$slug/media-coverage'
    | '/$slug/news'
    | '/$slug/notices'
    | '/$slug/organizational-chart'
    | '/$slug/public-representatives'
    | '/$slug/tenders'
    | '/admin/login'
    | '/$slug/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
  ScreenReaderRoute: typeof ScreenReaderRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screen-reader': {
      id: '/screen-reader'
      path: '/screen-reader'
      fullPath: '/screen-reader'
      preLoaderRoute: typeof ScreenReaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/tenders': {
      id: '/$slug/tenders'
      path: '/tenders'
      fullPath: '/$slug/tenders'
      preLoaderRoute: typeof SlugTendersRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/public-representatives': {
      id: '/$slug/public-representatives'
      path: '/public-representatives'
      fullPath: '/$slug/public-representatives'
      preLoaderRoute: typeof SlugPublicRepresentativesRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/organizational-chart': {
      id: '/$slug/organizational-chart'
      path: '/organizational-chart'
      fullPath: '/$slug/organizational-chart'
      preLoaderRoute: typeof SlugOrganizationalChartRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/notices': {
      id: '/$slug/notices'
      path: '/notices'
      fullPath: '/$slug/notices'
      preLoaderRoute: typeof SlugNoticesRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/news': {
      id: '/$slug/news'
      path: '/news'
      fullPath: '/$slug/news'
      preLoaderRoute: typeof SlugNewsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/media-coverage': {
      id: '/$slug/media-coverage'
      path: '/media-coverage'
      fullPath: '/$slug/media-coverage'
      preLoaderRoute: typeof SlugMediaCoverageRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/grievance': {
      id: '/$slug/grievance'
      path: '/grievance'
      fullPath: '/$slug/grievance'
      preLoaderRoute: typeof SlugGrievanceRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/gallery': {
      id: '/$slug/gallery'
      path: '/gallery'
      fullPath: '/$slug/gallery'
      preLoaderRoute: typeof SlugGalleryRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/departments': {
      id: '/$slug/departments'
      path: '/departments'
      fullPath: '/$slug/departments'
      preLoaderRoute: typeof SlugDepartmentsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/council': {
      id: '/$slug/council'
      path: '/council'
      fullPath: '/$slug/council'
      preLoaderRoute: typeof SlugCouncilRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/contact': {
      id: '/$slug/contact'
      path: '/contact'
      fullPath: '/$slug/contact'
      preLoaderRoute: typeof SlugContactRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/co-option-members': {
      id: '/$slug/co-option-members'
      path: '/co-option-members'
      fullPath: '/$slug/co-option-members'
      preLoaderRoute: typeof SlugCoOptionMembersRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/chairperson': {
      id: '/$slug/chairperson'
      path: '/chairperson'
      fullPath: '/$slug/chairperson'
      preLoaderRoute: typeof SlugChairpersonRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/about': {
      id: '/$slug/about'
      path: '/about'
      fullPath: '/$slug/about'
      preLoaderRoute: typeof SlugAboutRouteImport
      parentRoute: typeof SlugRoute
    }
  }
}

interface SlugRouteChildren {
  SlugAboutRoute: typeof SlugAboutRoute
  SlugChairpersonRoute: typeof SlugChairpersonRoute
  SlugCoOptionMembersRoute: typeof SlugCoOptionMembersRoute
  SlugContactRoute: typeof SlugContactRoute
  SlugCouncilRoute: typeof SlugCouncilRoute
  SlugDepartmentsRoute: typeof SlugDepartmentsRoute
  SlugGalleryRoute: typeof SlugGalleryRoute
  SlugGrievanceRoute: typeof SlugGrievanceRoute
  SlugMediaCoverageRoute: typeof SlugMediaCoverageRoute
  SlugNewsRoute: typeof SlugNewsRoute
  SlugNoticesRoute: typeof SlugNoticesRoute
  SlugOrganizationalChartRoute: typeof SlugOrganizationalChartRoute
  SlugPublicRepresentativesRoute: typeof SlugPublicRepresentativesRoute
  SlugTendersRoute: typeof SlugTendersRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugAboutRoute: SlugAboutRoute,
  SlugChairpersonRoute: SlugChairpersonRoute,
  SlugCoOptionMembersRoute: SlugCoOptionMembersRoute,
  SlugContactRoute: SlugContactRoute,
  SlugCouncilRoute: SlugCouncilRoute,
  SlugDepartmentsRoute: SlugDepartmentsRoute,
  SlugGalleryRoute: SlugGalleryRoute,
  SlugGrievanceRoute: SlugGrievanceRoute,
  SlugMediaCoverageRoute: SlugMediaCoverageRoute,
  SlugNewsRoute: SlugNewsRoute,
  SlugNoticesRoute: SlugNoticesRoute,
  SlugOrganizationalChartRoute: SlugOrganizationalChartRoute,
  SlugPublicRepresentativesRoute: SlugPublicRepresentativesRoute,
  SlugTendersRoute: SlugTendersRoute,
  SlugIndexRoute: SlugIndexRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
  ScreenReaderRoute: ScreenReaderRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
