/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug.index'
import { Route as SlugNoticesRouteImport } from './routes/$slug.notices'
import { Route as SlugNewsRouteImport } from './routes/$slug.news'
import { Route as SlugDepartmentsRouteImport } from './routes/$slug.departments'
import { Route as SlugAboutRouteImport } from './routes/$slug.about'

const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SlugRoute,
} as any)
const SlugNoticesRoute = SlugNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => SlugRoute,
} as any)
const SlugNewsRoute = SlugNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => SlugRoute,
} as any)
const SlugDepartmentsRoute = SlugDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => SlugRoute,
} as any)
const SlugAboutRoute = SlugAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/$slug/about': typeof SlugAboutRoute
  '/$slug/departments': typeof SlugDepartmentsRoute
  '/$slug/news': typeof SlugNewsRoute
  '/$slug/notices': typeof SlugNoticesRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug/about': typeof SlugAboutRoute
  '/$slug/departments': typeof SlugDepartmentsRoute
  '/$slug/news': typeof SlugNewsRoute
  '/$slug/notices': typeof SlugNoticesRoute
  '/$slug': typeof SlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRouteWithChildren
  '/$slug/about': typeof SlugAboutRoute
  '/$slug/departments': typeof SlugDepartmentsRoute
  '/$slug/news': typeof SlugNewsRoute
  '/$slug/notices': typeof SlugNoticesRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/$slug/about'
    | '/$slug/departments'
    | '/$slug/news'
    | '/$slug/notices'
    | '/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug/about'
    | '/$slug/departments'
    | '/$slug/news'
    | '/$slug/notices'
    | '/$slug'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/$slug/about'
    | '/$slug/departments'
    | '/$slug/news'
    | '/$slug/notices'
    | '/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/notices': {
      id: '/$slug/notices'
      path: '/notices'
      fullPath: '/$slug/notices'
      preLoaderRoute: typeof SlugNoticesRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/news': {
      id: '/$slug/news'
      path: '/news'
      fullPath: '/$slug/news'
      preLoaderRoute: typeof SlugNewsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/departments': {
      id: '/$slug/departments'
      path: '/departments'
      fullPath: '/$slug/departments'
      preLoaderRoute: typeof SlugDepartmentsRouteImport
      parentRoute: typeof SlugRoute
    }
    '/$slug/about': {
      id: '/$slug/about'
      path: '/about'
      fullPath: '/$slug/about'
      preLoaderRoute: typeof SlugAboutRouteImport
      parentRoute: typeof SlugRoute
    }
  }
}

interface SlugRouteChildren {
  SlugAboutRoute: typeof SlugAboutRoute
  SlugDepartmentsRoute: typeof SlugDepartmentsRoute
  SlugNewsRoute: typeof SlugNewsRoute
  SlugNoticesRoute: typeof SlugNoticesRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

const SlugRouteChildren: SlugRouteChildren = {
  SlugAboutRoute: SlugAboutRoute,
  SlugDepartmentsRoute: SlugDepartmentsRoute,
  SlugNewsRoute: SlugNewsRoute,
  SlugNoticesRoute: SlugNoticesRoute,
  SlugIndexRoute: SlugIndexRoute,
}

const SlugRouteWithChildren = SlugRoute._addFileChildren(SlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
